// Export all custom hooks
export { useHomeStats } from './useHomeStats';
export { useHomeHero } from './useHomeHero';
export { useHomeAbout } from './useHomeAbout';
export { useHomeQuality } from './useHomeQuality';
export { useHomeProducts } from './useHomeProducts';
export { useSpecialties } from './useSpecialties';
export { useSpecialtiesPage } from './useSpecialtiesPage';
export { useHomeSpecialties } from './useHomeSpecialties';
export { useProduct } from './useProduct';
export { useAwards } from './useAwards';
export { useAwardsPage } from './useAwardsPage';
export { useLeaders } from './useLeaders';
export { useTestimonials } from './useTestimonials';
export { useClients } from './useClients';
export { useClientsPage } from './useClientsPage';
export { useAbout } from './useAbout';
export { useContactUs } from './useContactUs';
export { useRequestDemo } from './useRequestDemo';
export { useCareers } from './useCareers';
export { useInvestorRelations } from './useInvestorRelations';
export { useOurPresence } from './useOurPresence';
export { useProductionFacility } from './useProductionFacility';
export { useQualityAssurance } from './useQualityAssurance';
export { useNavigation, type NavigationItem } from './useNavigation';
export { useFooter, type FooterSection, type FooterLink } from './useFooter';
export { useSocialLinks, type SocialLink } from './useSocialLinks';
export { useContactInfo, type ContactInfo } from './useContactInfo';
export { useFooterLogos } from './useFooterLogos';
export { useReusableContact } from './useReusableContact';
export { useOurProductsPage } from './useOurProductsPage';
export { useTermsAndConditions } from './useTermsAndConditions';
export { usePrivacyPolicy } from './usePrivacyPolicy';
export { useFaqs } from './useFaqs';

